[WIP] Find next free event
IOT-DSA/dslink-java-calendar pull request #16
Opened 2016-10-23 23:23 UTC by Pacane

2016-10-25 02:47 UTC, logangorence commented on src/main/java/org/dsa/iot/calendar/event/EventUtils.java
> +        for (int i = 0; i < events.size() - 1; ++i) {
Should this be using eventsNotOver?

2016-10-25 02:49 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/event/EventUtils.java
> +        for (int i = 0; i < events.size() - 1; ++i) {
Yes most likely.  This method was kind of on hold though.  Needed to get the time slot table done to finish it.

2016-10-25 02:51 UTC, azenla requested changes
Overall really good.

2016-10-25 02:51 UTC, kaendfinger commented on build.gradle
> +    compile group: 'junit', name: 'junit', version: '4.12'
Probably should use the same 'A:B:C' syntax here

2016-10-25 02:51 UTC, kaendfinger commented on src/main/java/org/dsa/iot/calendar/caldav/CalDAVCalendar.java
> +        java.util.Date start = Date.from(event.getStart());
Was this expanded to java.util.Date for a reason? Conflicting imports?

2016-10-25 02:51 UTC, kaendfinger commented on src/test/java/org/dsa/iot/calendar/event/TimeSlotTableTest.java
> +
Empty line

2016-10-25 02:51 UTC, kaendfinger commented on src/main/java/org/dsa/iot/calendar/Actions.java
> +                        e.printStackTrace();
Probably not good to print the stacktrace to stdio, need to use a logger or return error gracefully to the action.

2016-10-25 02:51 UTC, kaendfinger commented on src/main/java/org/dsa/iot/calendar/Actions.java
> +                        e.printStackTrace();
Probably not good to print the stacktrace to stdio, need to use a logger or return error gracefully to the action.

2016-10-25 02:51 UTC, kaendfinger commented on src/main/java/org/dsa/iot/calendar/Actions.java
>          EditEvent(final BaseCalendar calendar) {
Personally find it best to have a modifier here.

2016-10-25 02:52 UTC, logangorence commented on src/main/java/org/dsa/iot/calendar/caldav/CalDAVCalendar.java
> +        java.util.Date start = Date.from(event.getStart());
Yes, CalDAV has a class called Date too 👿

2016-10-25 02:52 UTC, logangorence commented on src/main/java/org/dsa/iot/calendar/caldav/CalDAVCalendar.java
> +        java.util.Date start = Date.from(event.getStart());
Yes, CalDAV has a class called Date too 👿

2016-10-26 01:32 UTC, Pacane commented
@kaendfinger @logangorence fixed the comments.

2016-10-26 21:03 UTC, azenla approved these changes

2016-10-27 19:01 UTC, merged