(WIP) Various clean up
IOT-DSA/dslink-java-calendar pull request #8
Opened 2016-10-21 00:30 UTC by logangorence

Made some various changes to cleanup getEvents(dateRange), and other beneficial changes, along with ones that were done and merged in already, I'll need to remove these before merging.

2016-10-21 00:37 UTC, Pacane requested changes

2016-10-21 00:37 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/abstractions/BaseCalendar.java
> +            if (event.checkInRange(start, end)) {
I'd rename this method to `isInRange` or `isBetween`

2016-10-21 00:37 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/abstractions/BaseCalendar.java
> +        List<DSAEvent> newEvents = new ArrayList<>();
I'd rename this `eventsInRange`.

2016-10-21 00:37 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/google/GoogleCalendar.java
> +        jsonGenerator = JacksonFactory.getDefaultInstance();
It'd be great if we used dependency injection where possible. Have you ever used Dagger or Guice?

2016-10-21 01:59 UTC, kubeliv commented on src/main/java/org/dsa/iot/calendar/google/GoogleCalendar.java
> +        jsonGenerator = JacksonFactory.getDefaultInstance();
@Pacane Is this something that we can visit in a later PR?

2016-10-21 02:01 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/google/GoogleCalendar.java
> +        jsonGenerator = JacksonFactory.getDefaultInstance();
Yes

2016-10-21 02:04 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/abstractions/BaseCalendar.java
> +            if (event.checkInRange(start, end)) {
I meant the `event.checkInRange` should be renamed to `event.isInRange`

2016-10-21 02:47 UTC, Pacane approved these changes

2016-10-22 19:36 UTC, kaendfinger commented on src/main/java/org/dsa/iot/calendar/google/GoogleCalendar.java
> +        } catch (Exception e) {
Generally you want to catch `Throwable` rather than `Exception`, just in case.

2016-10-22 19:42 UTC, merged

2016-10-22 19:47 UTC, Pacane commented on src/main/java/org/dsa/iot/calendar/google/GoogleCalendar.java
> +        } catch (Exception e) {
Never seen that pattern though.